# Generated by Django 4.0.3 on 2022-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amaestramientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='nombre_amaestramiento', max_length=30, null=True, verbose_name='nombre_amaestramiento')),
                ('codigo', models.CharField(blank=True, help_text='codigo de la sala o lugar', max_length=30, null=True, verbose_name='codigo de la sala o lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del departamento', max_length=30, null=True, verbose_name='Nombre del departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Planta_o_zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre de la sala o lugar', max_length=30, null=True, verbose_name='Nombre de la planta o zona')),
                ('departamento', models.ManyToManyField(blank=True, help_text='departamento de', max_length=30, null=True, to='espacios.departamento', verbose_name='departamento de')),
            ],
        ),
        migrations.CreateModel(
            name='Puertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Puerta de la sala o lugar', max_length=30, null=True, verbose_name='Puerta de la sala o lugar')),
                ('departamento', models.ManyToManyField(blank=True, help_text='departamento de', max_length=30, null=True, to='espacios.departamento', verbose_name='departamento de')),
                ('planta_o_zona', models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=30, null=True, to='espacios.planta_o_zona', verbose_name='acceso desde planta_o_zona')),
            ],
        ),
        migrations.CreateModel(
            name='llaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Puerta de la sala o lugar', max_length=30, null=True, verbose_name='Puerta de la sala o lugar')),
                ('codigo', models.CharField(blank=True, help_text='codigo de la sala o lugar', max_length=30, null=True, verbose_name='codigo de la sala o lugar')),
                ('posicion_de_llave_en_armario', models.CharField(blank=True, help_text='ubicacion en el armario', max_length=30, null=True, verbose_name='ubicacion en el armario')),
                ('amaestramiento', models.ManyToManyField(blank=True, help_text='Amaestramientos', max_length=30, null=True, to='espacios.amaestramientos', verbose_name='Amaestramientos')),
                ('planta_o_zona', models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=30, null=True, to='espacios.planta_o_zona', verbose_name='acceso desde planta_o_zona')),
            ],
        ),
        migrations.CreateModel(
            name='Habs_cuartos_salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre de la planta o zona', max_length=30, null=True, verbose_name='Nombre de la sala o lugar')),
                ('departamento', models.ManyToManyField(blank=True, help_text='departamento de', max_length=30, null=True, to='espacios.departamento', verbose_name='departamento de')),
                ('planta_o_zona', models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=30, null=True, to='espacios.planta_o_zona', verbose_name='acceso desde planta_o_zona')),
            ],
        ),
    ]
