# Generated by Django 4.0.3 on 2022-05-28 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amaestramientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='SSTT', help_text='nombre_amaestramiento', max_length=30, verbose_name='nombre_amaestramiento')),
                ('codigo', models.CharField(blank=True, default='0', help_text='codigo de la sala o lugar', max_length=30, verbose_name='codigo de la sala o lugar')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='SSTT', max_length=30, verbose_name='Nombre del departamento')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Planta_o_zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre de la sala o lugar', max_length=30, verbose_name='Nombre de la planta o zona')),
                ('departamento', models.ManyToManyField(blank=True, help_text='departamento de', max_length=30, to='espacios.departamentos', verbose_name='departamento de')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Puertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', help_text='Puerta de la sala o lugar', max_length=30, verbose_name='Puerta de la sala o lugar')),
                ('departamento', models.ManyToManyField(blank=True, help_text='departamento de', max_length=30, to='espacios.departamentos', verbose_name='departamento de')),
                ('planta_o_zona', models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=30, to='espacios.planta_o_zonas', verbose_name='acceso desde planta_o_zona')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='llaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='0', help_text='Puerta de la sala o lugar', max_length=30, verbose_name='Puerta de la sala o lugar')),
                ('codigo', models.CharField(blank=True, default='0', help_text='codigo de la sala o lugar', max_length=30, verbose_name='codigo de la sala o lugar')),
                ('posicion_de_llave_en_armario', models.CharField(blank=True, default='0', help_text='ubicacion en el armario', max_length=30, verbose_name='ubicacion en el armario')),
                ('maestra', models.ManyToManyField(blank=True, help_text='Amaestramientos', max_length=30, to='espacios.amaestramientos', verbose_name='Amaestramientos')),
                ('planta_o_zona', models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=30, to='espacios.planta_o_zonas', verbose_name='acceso desde planta_o_zona')),
                ('usuario_llave', models.ForeignKey(default=1, help_text='usuario_llave', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_llave', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Habs_cuartos_salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre de la planta o zona', max_length=30, verbose_name='Nombre de la sala o lugar')),
                ('departamento', models.ManyToManyField(blank=True, help_text='departamento de', max_length=30, to='espacios.departamentos', verbose_name='departamento de')),
                ('planta_o_zona', models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=30, to='espacios.planta_o_zonas', verbose_name='acceso desde planta_o_zona')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
