# Generated by Django 4.0.3 on 2022-05-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amaestramientos',
            name='codigo',
            field=models.CharField(blank=True, default='0', help_text='codigo de la sala o lugar', max_length=50, verbose_name='codigo de la sala o lugar'),
        ),
        migrations.AlterField(
            model_name='amaestramientos',
            name='nombre',
            field=models.CharField(blank=True, default='SSTT', help_text='nombre_amaestramiento', max_length=50, verbose_name='nombre_amaestramiento'),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre del departamento'),
        ),
        migrations.AlterField(
            model_name='habs_cuartos_salas',
            name='departamento',
            field=models.ManyToManyField(blank=True, help_text='departamento de', max_length=50, to='espacios.departamentos', verbose_name='departamento de'),
        ),
        migrations.AlterField(
            model_name='habs_cuartos_salas',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre de la planta o zona', max_length=50, verbose_name='Nombre de la sala o lugar'),
        ),
        migrations.AlterField(
            model_name='habs_cuartos_salas',
            name='planta_o_zona',
            field=models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=50, to='espacios.planta_o_zonas', verbose_name='acceso desde planta_o_zona'),
        ),
        migrations.AlterField(
            model_name='llaves',
            name='codigo',
            field=models.CharField(blank=True, default='0', help_text='codigo de la sala o lugar', max_length=50, verbose_name='codigo de la sala o lugar'),
        ),
        migrations.AlterField(
            model_name='llaves',
            name='maestra',
            field=models.ManyToManyField(blank=True, help_text='Amaestramientos', max_length=50, to='espacios.amaestramientos', verbose_name='Amaestramientos'),
        ),
        migrations.AlterField(
            model_name='llaves',
            name='nombre',
            field=models.CharField(blank=True, default='0', help_text='Puerta de la sala o lugar', max_length=50, verbose_name='Puerta de la sala o lugar'),
        ),
        migrations.AlterField(
            model_name='llaves',
            name='planta_o_zona',
            field=models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=50, to='espacios.planta_o_zonas', verbose_name='acceso desde planta_o_zona'),
        ),
        migrations.AlterField(
            model_name='llaves',
            name='posicion_de_llave_en_armario',
            field=models.CharField(blank=True, default='0', help_text='ubicacion en el armario', max_length=50, verbose_name='ubicacion en el armario'),
        ),
        migrations.AlterField(
            model_name='planta_o_zonas',
            name='departamento',
            field=models.ManyToManyField(blank=True, help_text='departamento de', max_length=50, to='espacios.departamentos', verbose_name='departamento de'),
        ),
        migrations.AlterField(
            model_name='planta_o_zonas',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre de la sala o lugar', max_length=50, verbose_name='Nombre de la planta o zona'),
        ),
        migrations.AlterField(
            model_name='puertas',
            name='departamento',
            field=models.ManyToManyField(blank=True, help_text='departamento de', max_length=50, to='espacios.departamentos', verbose_name='departamento de'),
        ),
        migrations.AlterField(
            model_name='puertas',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Puerta de la sala o lugar', max_length=50, verbose_name='Puerta de la sala o lugar'),
        ),
        migrations.AlterField(
            model_name='puertas',
            name='planta_o_zona',
            field=models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=50, to='espacios.planta_o_zonas', verbose_name='acceso desde planta_o_zona'),
        ),
    ]
