# Generated by Django 4.0.3 on 2022-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habs_cuartos_salas',
            name='departamento',
            field=models.ManyToManyField(blank=True, help_text='departamento de', max_length=30, to='espacios.departamento', verbose_name='departamento de'),
        ),
    ]
