# Generated by Django 4.0.3 on 2022-05-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_alter_habs_cuartos_salas_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habs_cuartos_salas',
            name='planta_o_zona',
            field=models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=30, to='espacios.planta_o_zona', verbose_name='acceso desde planta_o_zona'),
        ),
        migrations.AlterField(
            model_name='llaves',
            name='amaestramiento',
            field=models.ManyToManyField(blank=True, help_text='Amaestramientos', max_length=30, to='espacios.amaestramientos', verbose_name='Amaestramientos'),
        ),
        migrations.AlterField(
            model_name='llaves',
            name='planta_o_zona',
            field=models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=30, to='espacios.planta_o_zona', verbose_name='acceso desde planta_o_zona'),
        ),
        migrations.AlterField(
            model_name='puertas',
            name='departamento',
            field=models.ManyToManyField(blank=True, help_text='departamento de', max_length=30, to='espacios.departamento', verbose_name='departamento de'),
        ),
        migrations.AlterField(
            model_name='puertas',
            name='planta_o_zona',
            field=models.ManyToManyField(blank=True, help_text='acceso desde planta_o_zona', max_length=30, to='espacios.planta_o_zona', verbose_name='acceso desde planta_o_zona'),
        ),
    ]
