# Generated by Django 4.0.3 on 2022-06-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_amaestramientos_usuario_maestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='puertas',
            name='cuarto',
            field=models.ManyToManyField(blank=True, help_text='acceso a ...', max_length=50, to='espacios.habs_cuartos_salas', verbose_name='acceso a ...'),
        ),
    ]
