# Generated by Django 4.0.3 on 2022-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_alter_habs_cuartos_salas_planta_o_zona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta_o_zona',
            name='departamento',
            field=models.ManyToManyField(blank=True, help_text='departamento de', max_length=30, to='espacios.departamento', verbose_name='departamento de'),
        ),
    ]
