# Generated by Django 4.0.3 on 2022-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_puertas_cuarto'),
    ]

    operations = [
        migrations.AddField(
            model_name='habs_cuartos_salas',
            name='habitacion',
            field=models.BooleanField(default=False, help_text='Habitacion?', verbose_name='Habitacion?'),
        ),
    ]
