# Generated by Django 4.0.3 on 2022-06-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0005_habs_cuartos_salas_habitacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habs_cuartos_salas',
            new_name='Ubicaciones',
        ),
    ]
