# Generated by Django 4.0.3 on 2022-06-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0006_rename_habs_cuartos_salas_ubicaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planta_o_zonas',
            new_name='Zonas',
        ),
    ]
