# Generated by Django 4.0.3 on 2022-06-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0007_rename_planta_o_zonas_zonas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llaves',
            name='planta_o_zona',
        ),
        migrations.RemoveField(
            model_name='puertas',
            name='planta_o_zona',
        ),
        migrations.RemoveField(
            model_name='ubicaciones',
            name='planta_o_zona',
        ),
        migrations.AddField(
            model_name='llaves',
            name='zona',
            field=models.ManyToManyField(blank=True, help_text='acceso desde zona', max_length=50, to='espacios.zonas', verbose_name='acceso desde zona'),
        ),
        migrations.AddField(
            model_name='puertas',
            name='zona',
            field=models.ManyToManyField(blank=True, help_text='acceso desde zona', max_length=50, to='espacios.zonas', verbose_name='acceso desde zona'),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='zona',
            field=models.ManyToManyField(blank=True, help_text='acceso desde zona', max_length=50, to='espacios.zonas', verbose_name='acceso desde zona'),
        ),
    ]
