# Generated by Django 4.0.3 on 2022-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0008_remove_llaves_planta_o_zona_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puertas',
            old_name='cuarto',
            new_name='ubicacion',
        ),
        migrations.AlterField(
            model_name='amaestramientos',
            name='codigo',
            field=models.CharField(blank=True, default='0', help_text='codigo de la ubicacion', max_length=50, verbose_name='codigo de la ubicacion'),
        ),
        migrations.AlterField(
            model_name='llaves',
            name='codigo',
            field=models.CharField(blank=True, default='0', help_text='codigo de la ubicacion', max_length=50, verbose_name='codigo de la ubicacion'),
        ),
        migrations.AlterField(
            model_name='llaves',
            name='nombre',
            field=models.CharField(blank=True, default='0', help_text='Puerta de la ubicacion', max_length=50, verbose_name='Puerta de la ubicacion'),
        ),
        migrations.AlterField(
            model_name='puertas',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Puerta de la ubicacion', max_length=50, verbose_name='Puerta de la ubicacion'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre de la zona', max_length=50, verbose_name='Nombre de la ubicacion'),
        ),
        migrations.AlterField(
            model_name='zonas',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre de la ubicacion', max_length=50, verbose_name='Nombre de la zona'),
        ),
    ]
