# Generated by Django 4.0.3 on 2022-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0009_rename_cuarto_puertas_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaves',
            name='num_bombillo',
            field=models.IntegerField(blank=True, default=0, help_text='Numero de bombillo', verbose_name='numero de bombillo'),
        ),
    ]
