# Generated by Django 4.0.3 on 2022-06-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0010_llaves_num_bombillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaves',
            name='ubicacion',
            field=models.ManyToManyField(blank=True, default='0', help_text='Llave de la ubicacion', max_length=50, to='espacios.ubicaciones', verbose_name='Llave de la ubicacion'),
        ),
    ]
