# Generated by Django 4.0.3 on 2022-06-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0011_llaves_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', help_text='Equipo o instalacion', max_length=50, verbose_name='Equipo o instalacion')),
                ('departamento', models.ManyToManyField(blank=True, help_text='departamento de', max_length=50, to='espacios.departamentos', verbose_name='departamento de')),
                ('ubicacion', models.ManyToManyField(blank=True, help_text='acceso a ...', max_length=50, to='espacios.ubicaciones', verbose_name='acceso a ...')),
                ('zona', models.ManyToManyField(blank=True, help_text='acceso desde zona', max_length=50, to='espacios.zonas', verbose_name='acceso desde zona')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Puertas',
        ),
    ]
