# Generated by Django 4.0.3 on 2022-06-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0012_elementos_delete_puertas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicaciones',
            old_name='habitacion',
            new_name='alojamiento',
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='AyB',
            field=models.BooleanField(default=False, help_text='AyB?', verbose_name='AyB?'),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='General',
            field=models.BooleanField(default=False, help_text='General?', verbose_name='General?'),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='otro',
            field=models.BooleanField(default=False, help_text='Otro?', verbose_name='Otro?'),
        ),
    ]
