# Generated by Django 2.2.1 on 2019-06-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0008_ot_trabajos_fecha_hora_cambio_tra'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_temp_minibar',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ot_Temp_Minibar', to='partes.Ot_Ubicaciones', verbose_name='Ubicacion minibar'),
        ),
        migrations.AlterField(
            model_name='ot_temp_clima_interior',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ot_Temp_Clima_Interior', to='partes.Ot_Ubicaciones', verbose_name='Ubicacion'),
        ),
    ]
