# Generated by Django 2.2.1 on 2019-06-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20190611_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_pedido_material',
            name='estado_ot',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Pedido', 'Pedido'), ('Denegado', 'Denegado'), ('Inversion', 'Inversion'), ('En espera', 'En espera'), ('Otro', 'Otro')], default='Pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='ot_temp_clima_interior',
            name='Caudal_de_aire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
