# Generated by Django 2.2.1 on 2019-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20190616_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot_temp_clima_interior',
            name='Caudal_de_aire',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ot_temp_clima_interior',
            name='Temp_Impulsion_Agua_Caliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ot_temp_clima_interior',
            name='Temp_Impulsion_Agua_Fria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ot_temp_clima_interior',
            name='Temp_Retorno_Agua_Caliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ot_temp_clima_interior',
            name='Temp_Retorno_Agua_Fria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
