# Generated by Django 2.1.5 on 2019-01-14 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ot_Elementos',
            fields=[
                ('elemento_el', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ot_Etiquetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta_et', models.CharField(blank=True, default='', help_text='Poner una etiqueta a este parte', max_length=30, verbose_name='Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Ot_Parte',
            fields=[
                ('num_ot', models.AutoField(help_text='numero de orden de trabajo', primary_key=True, serialize=False, verbose_name='numero de Ot')),
                ('descripcion_ot', models.CharField(help_text='Descripción del problema', max_length=300, verbose_name='Descripción')),
                ('fecha_ot', models.DateField(auto_now_add=True, verbose_name='Fecha del parte')),
                ('fecha_cambio_ot', models.DateField(auto_now=True, verbose_name='Fecha del ultimo cambio')),
                ('prioridad_ot', models.CharField(blank=True, choices=[('1', 'Urgente'), ('2', 'Daños'), ('3', 'Molesta al cliente'), ('4', 'Mala imagen'), ('5', 'Legal')], default='2', max_length=30)),
                ('estado_ot', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Terminado', 'Terminado'), ('Pausado', 'Pausado'), ('Otro', 'Otro')], default='Pendiente', max_length=30)),
                ('recursos_ot', models.CharField(choices=[('Propios', 'Propios'), ('externos', 'externos'), ('mixtos', 'mixtos')], default='Propios', max_length=30)),
                ('etiqueta_ot', models.CharField(blank=True, default='', help_text='Poner una etiqueta a este parte', max_length=30)),
                ('notas_ot', models.CharField(blank=True, default='', help_text='Poner una nota a este parte', max_length=30)),
                ('tipo_aviso_ot', models.CharField(choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo'), ('Legal', 'Legal'), ('Servicio o Ayuda', 'Servicio o Ayuda'), ('Atencion cliente', 'Atencion cliente')], default='Correctivo', max_length=30)),
                ('elemento_ot', models.ForeignKey(help_text='Elemento, Objeto o Aparato', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partes.Ot_Elementos', verbose_name='Elemento')),
            ],
            options={
                'ordering': ['-num_ot'],
            },
        ),
        migrations.CreateModel(
            name='Ot_Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_pe', models.CharField(default='', help_text='Obj', max_length=30, verbose_name='Ele')),
            ],
        ),
        migrations.CreateModel(
            name='Ot_Trabajos',
            fields=[
                ('num_tra', models.AutoField(help_text='Numero de Trabajo', primary_key=True, serialize=False, verbose_name='Numero TRA')),
                ('descripcion_tra', models.CharField(help_text='Descripción del Trabajo', max_length=300, verbose_name='Descripción')),
                ('fecha_tra', models.DateField(auto_now_add=True, verbose_name='Fecha del trabajo')),
                ('fecha_cambio_tra', models.DateField(auto_now=True, verbose_name='Fecha del ultimo cambio')),
                ('num_ot_tra', models.ForeignKey(help_text='Num de parte', on_delete=django.db.models.deletion.CASCADE, to='partes.Ot_Parte', verbose_name='Num de parte')),
            ],
        ),
        migrations.CreateModel(
            name='Ot_Ubicaciones',
            fields=[
                ('ubicacion_ub', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='ot_parte',
            name='ubicacion_ot',
            field=models.ForeignKey(help_text='Numero de Habitación o ubicación', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partes.Ot_Ubicaciones', verbose_name='Ubicación'),
        ),
    ]
