# Generated by Django 2.1.5 on 2019-02-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ot_trabajos',
            options={'ordering': ['-fecha_cambio_tra']},
        ),
        migrations.AlterField(
            model_name='ot_parte',
            name='estado_ot',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Terminado', 'Terminado'), ('Inversion', 'Inversion'), ('En espera', 'En espera'), ('Otro', 'Otro')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='ot_parte',
            name='prioridad_ot',
            field=models.CharField(blank=True, choices=[('1', 'Urgente'), ('2', 'Provoca daños'), ('3', 'Molesta al cliente'), ('4', 'Mala imagen'), ('5', 'Legal')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='ot_parte',
            name='recursos_ot',
            field=models.CharField(choices=[('Propios', 'Recursos Propios'), ('externos', 'Recursos externos'), ('mixtos', 'mixtos')], default='Propios', max_length=30),
        ),
    ]
