# Generated by Django 2.1.4 on 2019-03-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0005_auto_20190303_1819'),
        ('partes', '0005_auto_20190303_1810'),
    ]

    operations = [
    ]
