# Generated by Django 2.1.5 on 2019-03-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0006_merge_20190303_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_parte',
            name='fecha_hora_cambio_ot',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha y hora del ultimo cambio'),
        ),
    ]
