# Generated by Django 2.1.5 on 2019-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0007_ot_parte_fecha_hora_cambio_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_trabajos',
            name='fecha_hora_cambio_tra',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha y hora del ultimo cambio'),
        ),
    ]
