# Generated by Django 4.0.3 on 2022-05-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0008_ot_trabajos_fecha_hora_cambio_tra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partes_y_trabajos',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('partes.ot_parte',),
        ),
    ]
