# Generated by Django 4.0.3 on 2022-05-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0010_delete_partes_y_trabajos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_parte',
            name='Usuario_ot',
            field=models.CharField(blank=True, default='', help_text='usuario que ha hecho este parte', max_length=30),
        ),
        migrations.AddField(
            model_name='ot_trabajos',
            name='Usuario_tra',
            field=models.CharField(blank=True, default='', help_text='usuario que ha hecho este trabajo', max_length=30),
        ),
    ]
