# Generated by Django 4.0.3 on 2022-05-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0011_ot_parte_usuario_ot_ot_trabajos_usuario_tra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_pedidos',
            name='Usuario_pe',
            field=models.CharField(blank=True, default='', help_text='usuario que ha hecho este Pedido', max_length=30),
        ),
    ]
