# Generated by Django 4.0.3 on 2022-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0012_ot_pedidos_usuario_pe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_parte',
            name='Tecnico_ot',
            field=models.CharField(blank=True, default='', help_text='Tecnico que tiene este parte', max_length=30),
        ),
    ]
