# Generated by Django 4.0.3 on 2022-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0013_ot_parte_tecnico_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot_parte',
            name='fecha_hora_terminado_ot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de la terminacion del parte'),
        ),
    ]
