# Generated by Django 4.0.3 on 2022-05-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0019_alter_ot_parte_tecnico_ot_alter_ot_parte_usuario_ot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot_parte',
            name='Tecnico_ot',
        ),
        migrations.RemoveField(
            model_name='ot_parte',
            name='Usuario_ot',
        ),
    ]
