# Generated by Django 4.0.3 on 2022-05-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0020_remove_ot_parte_tecnico_ot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot_pedidos',
            name='Usuario_pe',
        ),
        migrations.RemoveField(
            model_name='ot_trabajos',
            name='Usuario_tra',
        ),
    ]
