# Generated by Django 4.0.3 on 2022-05-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partes', '0023_ot_parte_tecnico_ot_ot_parte_usuario_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_pedidos',
            name='Usuario_pe',
            field=models.ForeignKey(default=1, help_text='usuario que ha hecho este Pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Usuario_pe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ot_trabajos',
            name='Usuario_tra',
            field=models.ForeignKey(default=1, help_text='usuario que ha hecho este trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Usuario_tra', to=settings.AUTH_USER_MODEL),
        ),
    ]
