# Generated by Django 4.0.3 on 2022-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0026_alter_ot_parte_tecnico_fin_parte_ot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_elementos',
            name='elemento_en_AyB',
            field=models.BooleanField(default=False, help_text='Está en AyB?', verbose_name='Está en AyB?'),
        ),
        migrations.AddField(
            model_name='ot_elementos',
            name='elemento_en_hab',
            field=models.BooleanField(default=False, help_text='Está en hab?', verbose_name='Está en hab?'),
        ),
        migrations.AddField(
            model_name='ot_elementos',
            name='elemento_en_varios',
            field=models.BooleanField(default=False, help_text='Está en varios?', verbose_name='Está en varios?'),
        ),
    ]
