# Generated by Django 4.0.3 on 2022-06-15 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('espacios', '0013_rename_habitacion_ubicaciones_alojamiento_and_more'),
        ('partes', '0027_ot_elementos_elemento_en_ayb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estados', models.CharField(max_length=30, null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del problema', max_length=300, verbose_name='Descripción')),
                ('recusos_propios', models.BooleanField(default=True, help_text='Recursos propios', verbose_name='Recursos propios')),
                ('notas', models.CharField(blank=True, default='', help_text='Poner una nota a este parte', max_length=30)),
                ('fecha_parte', models.DateField(auto_now_add=True, verbose_name='Fecha del parte')),
                ('fecha_hora_cambio', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora del ultimo cambio')),
                ('fecha_hora_terminado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de la terminacion del parte')),
                ('Tecnico_asignado', models.ForeignKey(blank=True, default=1, help_text='Tecnico que tiene este parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tecnico', to=settings.AUTH_USER_MODEL)),
                ('Tecnico_fin_parte', models.ForeignKey(blank=True, default=1, help_text='Tecnico que tiene este parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tecnico_fin_parte', to=settings.AUTH_USER_MODEL)),
                ('Usuario', models.ForeignKey(blank=True, default=1, help_text='usuario que ha hecho este parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
                ('elemento', models.ForeignKey(help_text='Elemento, Objeto o Aparato', max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='espacios.elementos', verbose_name='Elemento')),
                ('estado_ot', models.ForeignKey(default='Pendiente', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partes.estados')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pedido', models.IntegerField(blank=True, default=0, help_text='num_pedido', verbose_name='num_pedido')),
                ('nombre_empresa', models.CharField(default='', help_text='nombre_empresa', max_length=50, verbose_name='nombre_empresa')),
                ('descrip_trabajo', models.CharField(default='', help_text='nombre_empresa', max_length=50, verbose_name='nombre_empresa')),
            ],
            options={
                'ordering': ['-num_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridades', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.RemoveField(
            model_name='ot_parte',
            name='fecha_cambio_ot',
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tra', models.CharField(help_text='Descripción del Trabajo', max_length=300, verbose_name='Descripción')),
                ('fecha_tra', models.DateField(auto_now_add=True, verbose_name='Fecha del trabajo')),
                ('fecha_cambio_tra', models.DateField(auto_now=True, verbose_name='Fecha del ultimo cambio')),
                ('fecha_hora_cambio_tra', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora del ultimo cambio')),
                ('num_parte_tra', models.ForeignKey(help_text='Num de parte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partes.parte', verbose_name='Num de parte')),
                ('tecnico_tra', models.ForeignKey(default=1, help_text='usuario que ha hecho este trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico_tra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='parte',
            name='pedido',
            field=models.ForeignKey(help_text='num_pedido', max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partes.pedido', verbose_name='num_pedido'),
        ),
        migrations.AddField(
            model_name='parte',
            name='prioridad_ot',
            field=models.ForeignKey(blank=True,  max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partes.prioridad'),
        ),
        migrations.AddField(
            model_name='parte',
            name='ubicacion',
            field=models.ForeignKey(help_text='Numero de Habitación o ubicación', max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='espacios.ubicaciones', verbose_name='Ubicación'),
        ),
    ]
