# Generated by Django 4.0.3 on 2022-06-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0030_alter_parte_prioridad_ot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parte',
            old_name='estado_ot',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='parte',
            old_name='prioridad_ot',
            new_name='prioridad',
        ),
    ]
