# Generated by Django 4.0.3 on 2022-06-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0033_ot_parte_fecha_cambio_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descrip_trabajo',
            field=models.CharField(blank=True, default='', help_text='nombre_empresa', max_length=50, verbose_name='nombre_empresa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_empresa',
            field=models.CharField(blank=True, default='', help_text='nombre_empresa', max_length=50, verbose_name='nombre_empresa'),
        ),
    ]
