# Generated by Django 2.1.5 on 2019-03-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiscGrMañana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PiscGrMañana_Tecnico', models.CharField(default='David', help_text='Nombre del Técnico', max_length=300, verbose_name='Tecnico')),
                ('PiscGrMañana_Fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del Registro')),
                ('PiscGrMañana_FechaHora', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora del ultimo cambio')),
                ('PiscGrMañana_Ph', models.DecimalField(decimal_places=2, help_text='Ph', max_digits=2, verbose_name='PiscGrMañana_Ph')),
                ('PiscGrMañana_CloroLibre', models.DecimalField(decimal_places=2, help_text='Cloro Libre', max_digits=2, verbose_name='PiscGrMañana_Libre')),
                ('PiscGrMañana_CloroTotal', models.DecimalField(decimal_places=2, help_text='Cloro Total', max_digits=2, null=True, verbose_name='PiscGrMañana_Total')),
                ('PiscGrMañana_Transparencia', models.DecimalField(decimal_places=2, default=1, help_text='Transparencia', max_digits=2, null=True, verbose_name='PiscGrMañana_Transparencia')),
                ('PiscGrMañana_Turbidez', models.DecimalField(decimal_places=2, default=1, help_text='Turbidez', max_digits=2, verbose_name='PiscGrMañana_Turbidez')),
                ('PiscGrMañana_Incidencias', models.CharField(help_text='Descripción de la Incidencia', max_length=300, verbose_name='PiscGrMañana_Incidencias')),
            ],
        ),
    ]
